#!/bin/bash


sudo pacman -Syyu git base-devel

git clone https://aur.archlinux.org/yay-bin.git

cd yay-bin

makepkg -si

cd ~/ 

 
yay -Syyu tmux fzf sxiv dmenu wget fish ranger htop rofi wofi bpytop zsh neovim npm nodejs python-pipx kitty waybar swayfx spotify thorium-browser-bin firefox swaybg swaync python-pywal 

git clone https://github.com/fruity-fkf/dott
git clone https://github.com/fruity-fkf/fishy

git clone https://github.com/fruity-fkf/wallpapers

